### ISSUE TITLE
The "Strawman" as an ABC?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [ioos/APIRUS#4]
Maybe the way to specify our API is with an Abstract Base Class:

https://docs.python.org/2/library/abc.html

Maybe that's getting too formal, but it might help us structure our thoughts, and we could even provide really trivial implementations for use in testing, experimenting with the API, etc.

**Comment by ocefpaf** [comment]
That might be a good idea if we find a champion to execute it.  I guess we do not have the man power right now for it...

**Comment by ChrisBarker-NOAA** [comment]
Well, there is always that.

but if you are writing down an API, writting it as Python code in an ABC is about the same amoutn of work....

Kind of like: why write pseudo code is you can just write Python?

Maybe I'll make a start....

**Comment by ocefpaf** [comment]
> Kind of like: why write pseudo code is you can just write Python?

:+1:

**Comment by ChrisBarker-NOAA** [comment]
OK -- file added -- only a start, but it's a place to put methods when we have them.
